filter:
    excluded_paths:
        - tests/*
build:
    nodes:
        analysis:
            environment:
                php:
                    version: 8.1
            tests:
                override:
                    - command: php-scrutinizer-run
