environments:
    php:
        prefer_dist: true

filter:
    excluded_paths:
        - tests/*
build:
    nodes:
        analysis:
            tests:
                override:
                    - command: php-scrutinizer-run
